#!/bin/sh

# 获取提交信息文件路径
commit_msg_file=$(git rev-parse --git-dir)/COMMIT_EDITMSG

# 读取提交信息内容
commit_msg=$(cat "$commit_msg_file")

# 输出提交信息内容（可选）
echo "Received commit message: $commit_msg"

npm run lint

